### ISSUE TITLE
Array sizes are not enforced on writing the structure instance

### ISSUE THREAD

**Issue by skarndev** [fox-it/dissect.cstruct#22]
Is there any particular reason there is no validation performed on the array sizes for static structures, where array size is also static?

It sort of produces the mismatch between what is actually written and the type schema.

**Comment by Schamper** [comment]
No particular reason, most likely just an oversight and/or never was an issue in our current use cases. However it does sound like a nice improvement! Feel free to submit a PR for this, otherwise we'll see if we can add this in ourselves soon.

I actually believe there are quite a few quality of life improvements that can be made in our writing functionality, but they often get less attention since our primary use case for cstruct is parsing. The few times we use it for writing, we tend to work around some of these issues in the surrounding code and we forget to fix it in cstruct itself. I.e. sane default values for empty fields.

If you run into any more problems or possible improvements, please do create more GitHub issues!
